import assert from 'node:assert/strict';
import { createHash, randomUUID } from 'node:crypto';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { OnlineStorage, type StoredProfile } from '../server/storage';
import { AccountLimiter, hashPassword, username, validPassword, verifyPassword } from '../server/accounts';

const root = resolve('.shots', `storage-${randomUUID()}`);
mkdirSync(root, { recursive: true });
const legacy = resolve(root, 'legacy.json');
const dbPath = resolve(root, 'online.sqlite');
const profile = (id: string, code: string): StoredProfile => ({ id, code, name: `Test ${id}`, tokenHash: createHash('sha256').update(id).digest('hex'), rating: 1000, wins: 0, losses: 0, friends: [] });
const a = profile('left', 'ABC123');
const b = profile('right', 'DEF456');
a.friends.push(b.id); b.friends.push(a.id);
const source = JSON.stringify([a, b]);
writeFileSync(legacy, source);
let storage = new OnlineStorage(dbPath, legacy);
assert.deepEqual(storage.profiles(), [a, b]);
assert.equal(readFileSync(legacy, 'utf8'), source, 'migration must retain the source unchanged');

const password = 'An example passphrase for this test';
const hash = await hashPassword(password);
assert.notEqual(hash, password);
assert.notEqual(hash, await hashPassword(password), 'hashes must have independent salts');
assert(await verifyPassword(password, hash));
assert.equal(await verifyPassword('An incorrect example passphrase', hash), false);
assert.equal(await verifyPassword(password, undefined), false);
assert.equal(username(' Sketch_Commander '), 'sketch_commander');
assert.equal(username('a b'), null);
assert(validPassword('long enough password'));
assert.equal(validPassword('short'), false);
assert.equal(validPassword('x'.repeat(129)), false);
assert(storage.register(a, 'sketch_commander', hash));
assert.equal(storage.register(b, 'sketch_commander', hash), false);
assert.equal(storage.account(b.id), null);

const finishedAt = new Date().toISOString();
const match = { id: 'match-1', left: a.id, right: b.id, winner: a.id, mode: 'ranked' as const, seed: 123, reason: 'forfeit', finishedAt };
const win = { ...a, rating: 1016, wins: 1 };
const loss = { ...b, rating: 984, losses: 1 };
const result = (won: boolean) => ({ matchId: match.id, finishedAt, opponent: { id: won ? b.id : a.id, name: won ? b.name : a.name }, won, mode: match.mode, reason: match.reason, ratingDelta: won ? 16 : -16, rating: won ? 1016 : 984, seconds: 30, kills: 2, losses: 1, peakAge: 0 });
assert(storage.finishMatch(match, [win, loss], [result(true), result(false)]));
assert.equal(storage.finishMatch(match, [win, loss], [result(true), result(false)]), false, 'duplicate settlement must not pay again');
assert.equal(storage.history(a.id).length, 1);
assert.equal(storage.history(b.id)[0].won, false);
// A missing participant forces rollback of the match, ratings and result rows.
assert.throws(() => storage.finishMatch({ ...match, id: 'bad', right: 'missing' }, [{ ...win, rating: 1200 }, loss], [result(true), result(false)]));
assert.equal(storage.profiles().find((p) => p.id === a.id)?.rating, 1016);
assert.equal(storage.db.prepare("SELECT id FROM matches WHERE id = 'bad'").get(), undefined);
await storage.backup(resolve(root, 'backup.sqlite'));
storage.close();
// Later source corruption cannot re-import or overwrite an already migrated database.
writeFileSync(legacy, '{ damaged');
storage = new OnlineStorage(dbPath, legacy);
assert.equal(storage.profiles().find((p) => p.id === a.id)?.rating, 1016);
assert.equal(storage.findAccount('sketch_commander')?.passwordHash, hash);
assert.equal(storage.history(a.id)[0].ratingDelta, 16);
storage.close();
const saved = new OnlineStorage(resolve(root, 'backup.sqlite'));
assert.equal(saved.history(a.id).length, 1); saved.close();

const corrupt = resolve(root, 'corrupt.json');
writeFileSync(corrupt, '{ damaged');
assert.throws(() => new OnlineStorage(resolve(root, 'corrupt.sqlite'), corrupt));
assert.equal(readFileSync(corrupt, 'utf8'), '{ damaged');
writeFileSync(corrupt, source);
const repaired = new OnlineStorage(resolve(root, 'corrupt.sqlite'), corrupt);
assert.equal(repaired.profiles().length, 2); repaired.close();
writeFileSync(corrupt, JSON.stringify([{ ...a, rating: 'tampered' }]));
assert.throws(() => new OnlineStorage(resolve(root, 'invalid.sqlite'), corrupt));
const limiter = new AccountLimiter(2, 1000);
assert(limiter.allow('ip-one', 'name-one', 0));
assert(limiter.allow('ip-one', 'name-two', 1));
assert.equal(limiter.allow('ip-one', 'name-three', 2), false);
assert(limiter.allow('ip-two', 'name-one', 3));
assert.equal(limiter.allow('ip-three', 'name-one', 4), false, 'username limit must cover different connections');
assert(limiter.allow('ip-one', 'name-one', 1001));
console.log('Online storage passed: safe legacy migration, salted passwords, transactional rating/results, duplicate guard, restart, live backup and bounded account limits.');
